# Assignment 18: Text Vectorization Techniques

Dataset Name: TMDB 5000 Movie Dataset

Kaggle Link: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

In [283]:
import pandas as pd

In [284]:
df = pd.read_csv('./IMDB_cleaned.csv')

In [285]:
data = df.copy()

In [286]:
data.head()

,review,final_clean_text
0,one of the other reviewers has mentioned that ...,one reviewer mention watch oz episode youll ho...
1,a wonderful little production br br the filmin...,wonderful little production film technique una...
2,i thought this was a wonderful way to spend ti...,think wonderful way spend time hot summer week...
3,basically theres a family where a little boy j...,basically there family little boy jake think t...
4,petter matteis love in the time of money is a ...,petter matteis love time money visually stunni...


In [287]:
data.shape

(50000, 2)

## Task 1: Manula One-Hot Encoding

In [288]:
sentences = df["final_clean_text"].dropna().head(10).tolist()

for sentence in sentences:
    print(sentence)

one reviewer mention watch oz episode youll hook right exactly happen methe first thing strike oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use wordit call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home manyaryans muslims gangsta latino christian italian irish moreso scuffle death stare dodgy dealing shady agreement never far awayi would say main appeal show due fact go show wouldnt dare forget pretty picture paint mainstream audience forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watch developed taste oz get accustomed high level graphic violence violence injustice crook guard wholl sell nickel inmates wholl kill order get away well mannered middle class inmate turn prison bitch due lack street 

In [289]:
# Create vocabulary
vocabulary = set()
for sentence in sentences:
    words = sentence.split()
    for word in words:
        vocabulary.add(word)
vocabulary = sorted(list(vocabulary))

print(vocabulary)

['accustomed', 'act', 'action', 'actor', 'addiction', 'adrian', 'adventureoh', 'agenda', 'agreement', 'air', 'alivewe', 'allen', 'alltime', 'almost', 'also', 'amazing', 'another', 'anxiously', 'anymore', 'appeal', 'argue', 'around', 'arthur', 'audience', 'average', 'await', 'awaken', 'away', 'awayi', 'awful', 'back', 'bad', 'band', 'basically', 'become', 'believable', 'believe', 'best', 'bette', 'big', 'bitch', 'bite', 'black', 'boogeyman', 'bore', 'boring', 'boy', 'bread', 'brilliance', 'brilliant', 'bring', 'brutality', 'buscemi', 'call', 'camp', 'cant', 'career', 'carol', 'case', 'cast', 'cause', 'cell', 'change', 'character', 'charm', 'cheap', 'child', 'choose', 'christian', 'city', 'class', 'classic', 'closet', 'come', 'comeback', 'comedy', 'comfort', 'comfortable', 'comment', 'complete', 'concern', 'condition', 'connect', 'contact', 'continued', 'control', 'couldnt', 'country', 'creator', 'credit', 'crook', 'crown', 'dare', 'darker', 'date', 'davis', 'dawson', 'dealing', 'death',

In [290]:
one_hot_vectors = []

for sentence in sentences:
    words = sentence.split()
    vector = []
    for word in vocabulary:
        if word in words:
            vector.append(1)
        else:
            vector.append(0)
    
    one_hot_vectors.append(vector)

In [291]:
for i in range(len(sentences)):
    print('vectos', one_hot_vectors[i])

vectos [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [292]:
one_hot_matrix = pd.DataFrame(
    one_hot_vectors,
    columns=vocabulary
)

print(one_hot_matrix)

   accustomed  act  action  actor  addiction  adrian  adventureoh  agenda  \
0           1    0       0      0          0       0            0       1   
1           0    0       0      1          0       0            0       0   
2           0    0       0      0          1       0            0       0   
3           0    0       0      0          0       0            0       0   
4           0    1       1      0          0       1            0       0   
5           0    0       0      0          0       0            0       0   
6           0    0       0      0          0       0            1       0   
7           0    0       0      0          0       0            0       0   
8           0    1       0      0          0       0            0       0   
9           0    0       0      0          0       0            0       0   

   agreement  air  ...  wouldnt  wrench  write  year  york  youll  young  \
0          1    0  ...        1       0      0     0     0      1      0   


## Task 2: One Hot Encoding using Scikit Learn

In [293]:
from sklearn.feature_extraction.text import CountVectorizer

In [294]:
vectorizer = CountVectorizer(binary=True)

In [295]:
encoded_matrix = vectorizer.fit_transform(sentences)

Vocabulary

In [296]:
len(vectorizer.get_feature_names_out())

557

In [297]:
print(vectorizer.get_feature_names_out())

['accustomed' 'act' 'action' 'actor' 'addiction' 'adrian' 'adventureoh'
 'agenda' 'agreement' 'air' 'alivewe' 'allen' 'alltime' 'almost' 'also'
 'amazing' 'another' 'anxiously' 'anymore' 'appeal' 'argue' 'around'
 'arthur' 'audience' 'average' 'await' 'awaken' 'away' 'awayi' 'awful'
 'back' 'bad' 'band' 'basically' 'become' 'believable' 'believe' 'best'
 'bette' 'big' 'bitch' 'bite' 'black' 'boogeyman' 'bore' 'boring' 'boy'
 'bread' 'brilliance' 'brilliant' 'bring' 'brutality' 'buscemi' 'call'
 'camp' 'cant' 'career' 'carol' 'case' 'cast' 'cause' 'cell' 'change'
 'character' 'charm' 'cheap' 'child' 'choose' 'christian' 'city' 'class'
 'classic' 'closet' 'come' 'comeback' 'comedy' 'comfort' 'comfortable'
 'comment' 'complete' 'concern' 'condition' 'connect' 'contact'
 'continued' 'control' 'couldnt' 'country' 'creator' 'credit' 'crook'
 'crown' 'dare' 'darker' 'date' 'davis' 'dawson' 'dealing' 'death'
 'decade' 'decide' 'decides' 'decline' 'decorate' 'dedication' 'delight'
 'descent' 'd

### Encoded matrix

In [298]:
print(encoded_matrix.toarray())

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Part 2: Bag of Words(BoW)

## Task 3: Bag of Words Representation

In [299]:
from sklearn.feature_extraction.text import CountVectorizer

In [300]:
texts = df["final_clean_text"].fillna("")


In [301]:
bow = CountVectorizer()
bow_matrix = bow.fit_transform(texts)

In [302]:
bow_vocabulary = bow.get_feature_names_out()

len(bow_vocabulary)

203208

In [303]:
len(bow.vocabulary_)

203208

In [304]:
bow_matrix[:10].toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [305]:
bow_df = pd.DataFrame(
    bow_matrix[:5,:10].toarray(),
    columns=vocabulary[:10]
)

In [306]:
# Bow Dataframe 
bow_df

,accustomed,act,action,actor,addiction,adrian,adventureoh,agenda,agreement,air
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0


## Task 3: Calculate total Frequence

In [307]:
word_frequency = bow_matrix.sum(axis=0)
word_frequency = word_frequency.A1

In [308]:
frequency_df = pd.DataFrame({"word": bow_vocabulary,"frequency": word_frequency})
frequency_df.head()

,word,frequency
0,aa,20
1,aaa,15
2,aaaaaaaaaaaahhhhhhhhhhhhhh,1
3,aaaaaaaargh,1
4,aaaaaaah,1


In [309]:
top_10_words = frequency_df.sort_values(by="frequency",ascending=False).head(10)

In [310]:
top_10_words

,word,frequency
116802,movie,99025
63106,film,91482
126756,one,52678
106866,make,43490
102265,like,42240
156521,see,40574
71354,get,35068
73270,good,32473
180666,time,29551
28859,character,27573


In [311]:
least_frequent_words = frequency_df[frequency_df["frequency"] == 1]

In [312]:
print(len(least_frequent_words))

131447


In [313]:
least_frequent_words.head(20)

,word,frequency
2,aaaaaaaaaaaahhhhhhhhhhhhhh,1
3,aaaaaaaargh,1
4,aaaaaaah,1
5,aaaaaaahhhhhhggg,1
6,aaaaagh,1
7,aaaaah,1
8,aaaaargh,1
9,aaaaarrrrrrgggggghhhhhh,1
10,aaaaatchkah,1
11,aaaaaw,1


Note: Bag of Words represents each document using word counts. If a word appears multiple times in a document, its value will be higher. By adding the columns of the BoW matrix, we can calculate the total frequency of each word in the complete dataset. Therefore, BoW provides information about how often each word occurs.

# Part 3

## Task 5

### unigram

In [314]:
unigram_vectorizer = CountVectorizer(
    ngram_range=(1, 1)
)

In [315]:
unigram_matrix = unigram_vectorizer.fit_transform(texts)

In [316]:
unigram_vocabulary = unigram_vectorizer.get_feature_names_out()

In [317]:
len(unigram_vocabulary)

203208

In [318]:
unigram_matrix[:1, :10].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

### bigram

In [319]:
bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2)
)

In [320]:
bigram_matrix = bigram_vectorizer.fit_transform(texts)

In [321]:
bigram_vocabulary = bigram_vectorizer.get_feature_names_out()

In [322]:
len(unigram_vocabulary)

203208

In [323]:
print(bigram_matrix[:1, :10].toarray())

[[0 0 0 0 0 0 0 0 0 0]]


### trigramprint(trigram_matrix[:1, :10].toarray())

In [324]:
trigram_vectorizer = CountVectorizer(
    ngram_range=(3, 3)
)

In [325]:
trigram_matrix = trigram_vectorizer.fit_transform(texts)

In [326]:
trigram_vocabulary = trigram_vectorizer.get_feature_names_out()

In [327]:
len(trigram_vocabulary)

5314584

In [328]:
print(trigram_matrix[:1, :10].toarray())

[[0 0 0 0 0 0 0 0 0 0]]


### comparison of vocabulary size 

In [329]:
print("Unigram vocabularysize:", len(unigram_vocabulary))

print("Bigram vocabulary size:", len(bigram_vocabulary))

print("Trigram vocabulary size:", len(trigram_vocabulary))

Unigram vocabularysize: 203208
Bigram vocabulary size: 2893018
Trigram vocabulary size: 5314584


## Task 6

In [330]:
ngram_vectorizer = CountVectorizer(ngram_range=(1, 2))

In [331]:
ngram_matrix = ngram_vectorizer.fit_transform(texts)

In [332]:
ngram_vocabulary = (ngram_vectorizer.get_feature_names_out())

In [333]:
len(ngram_vocabulary)

3096226

In [334]:
ngram_vocabulary[:20]

array(['aa', 'aa act', 'aa antic', 'aa cultrehab', 'aa date', 'aa doctor',
       'aa group', 'aa jaega', 'aa level', 'aa meeting', 'aa meri',
       'aa milne', 'aa mindless', 'aa presentation', 'aa rating', 'aa uo',
       'aa violent', 'aa yet', 'aaa', 'aaa ball'], dtype=object)

In [335]:
ngram_matrix[:1, :20].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

# Part 4

### TASK 7

In [336]:
df = pd.read_csv("IMDB_cleaned.csv")

In [337]:
texts = df["final_clean_text"].fillna("")

In [338]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [339]:
tfidf_vectorizer = TfidfVectorizer()

In [340]:
tfidf_matrix = tfidf_vectorizer.fit_transform(texts)


In [341]:
tfidf_vocabulary = tfidf_vectorizer.get_feature_names_out()


In [342]:
len(tfidf_vocabulary)

203208

In [343]:
tfidf_vocabulary[:20]

array(['aa', 'aaa', 'aaaaaaaaaaaahhhhhhhhhhhhhh', 'aaaaaaaargh',
       'aaaaaaah', 'aaaaaaahhhhhhggg', 'aaaaagh', 'aaaaah', 'aaaaargh',
       'aaaaarrrrrrgggggghhhhhh', 'aaaaatchkah', 'aaaaaw', 'aaaahhhhhh',
       'aaaahhhhhhh', 'aaaand', 'aaaarrgh', 'aaaawwwwww', 'aaaggghhhhhhh',
       'aaaghi', 'aaah'], dtype=object)

In [344]:
print(tfidf_matrix.shape)



(50000, 203208)


## TASK 8

In [345]:
import numpy as np

In [346]:
average_tfidf = np.asarray(tfidf_matrix.mean(axis=0)).flatten()

In [347]:
tfidf_df = pd.DataFrame({"word": tfidf_vocabulary,"tfidf": average_tfidf})

In [348]:
tfidf_df.head()

,word,tfidf
0,aa,0.000046
1,aaa,0.000039
2,aaaaaaaaaaaahhhhhhhhhhhhhh,0.000004
3,aaaaaaaargh,0.000007
4,aaaaaaah,0.000003


In [349]:
bow_frequency = bow_matrix.sum(axis=0).A1

In [350]:
bow_frequency_df = pd.DataFrame({"word": bow_vocabulary,"bow_frequency": bow_frequency})

In [351]:
comparison_df = pd.merge(bow_frequency_df,tfidf_df,on="word")

In [352]:
comparison_df.head(10)

,word,bow_frequency,tfidf
0,aa,20,4.635925e-05
1,aaa,15,3.872018e-05
2,aaaaaaaaaaaahhhhhhhhhhhhhh,1,4.139042e-06
3,aaaaaaaargh,1,6.819697e-06
4,aaaaaaah,1,3.413846e-06
5,aaaaaaahhhhhhggg,1,5.785819e-06
6,aaaaagh,1,5.893113e-06
7,aaaaah,1,8.550280e-07
8,aaaaargh,1,2.919497e-06
9,aaaaarrrrrrgggggghhhhhh,1,4.730181e-06


In [353]:
top_10_bow_frequency = comparison_df.sort_values(by="bow_frequency",ascending=False).head(10)

In [354]:
top_10_bow_frequency

,word,bow_frequency,tfidf
116802,movie,99025,0.051190
63106,film,91482,0.042816
126756,one,52678,0.025478
106866,make,43490,0.022794
102265,like,42240,0.022911
156521,see,40574,0.023332
71354,get,35068,0.019745
73270,good,32473,0.020575
180666,time,29551,0.018100
28859,character,27573,0.017346


In [355]:
top_10_high_tfidef = comparison_df.sort_values(by="tfidf",ascending=False).head(10)

In [356]:
top_10_high_tfidef

,word,bow_frequency,tfidf
116802,movie,99025,0.051190
63106,film,91482,0.042816
126756,one,52678,0.025478
156521,see,40574,0.023332
102265,like,42240,0.022911
106866,make,43490,0.022794
73270,good,32473,0.020575
71354,get,35068,0.019745
13032,bad,24097,0.018987
194383,watch,25825,0.018955


In [357]:
to_10_low_tfidf_words    = comparison_df.sort_values(by="tfidf",ascending=True).head(10)

In [358]:
to_10_low_tfidf_words

,word,bow_frequency,tfidf
122233,nobles,1,3.714913e-07
78285,hardymatch,1,3.714913e-07
85274,hurracanrana,1,3.714913e-07
72484,gloated,1,3.714913e-07
100701,leftmatch,1,3.714913e-07
150136,rockfinally,1,3.714913e-07
175415,tannouncement,1,3.714913e-07
30625,chokeslammed,1,3.714913e-07
173151,suplexing,1,3.714913e-07
172959,superkicked,1,3.714913e-07


## TASK 9

## experiement with max_features

In [359]:
df = pd.read_csv("IMDB_cleaned.csv")

In [360]:

texts = df["final_clean_text"].fillna("")

In [361]:
vectorizer_1 = CountVectorizer(max_features=1000)

In [362]:
matrix_1 = vectorizer_1.fit_transform(texts)

In [363]:
vocab_1 = len(vectorizer_1.get_feature_names_out())


In [364]:
vocab_1

1000

In [365]:
vectorizer_2 = CountVectorizer(max_features=5000)
matrix_2 = vectorizer_2.fit_transform(texts)

In [366]:
vocab_2= len(vectorizer_2.get_feature_names_out())

In [367]:
vocab_2

5000

In [368]:
vectorizer_3 = CountVectorizer(max_features=10000)
matrix_3 = vectorizer_3.fit_transform(texts)

In [369]:
vocab_3= len(vectorizer_3.get_feature_names_out())

In [370]:
vocab_3

10000

### Observatin
- When Max_feature is increased, then vocabulary size can also increase, it limits the max no. of features that can be selected

## Experiment 2 with min_df

In [371]:
vectorizer_4 = CountVectorizer(min_df=1)

matrix_4 = vectorizer_4.fit_transform(texts)

In [372]:
vocab4= len(vectorizer_4.get_feature_names_out())

In [373]:
vocab4

203208

In [374]:
vectorizer_5 = CountVectorizer(min_df=5)

matrix_5 = vectorizer_5.fit_transform(texts)

In [375]:
vocab5= len(vectorizer_5.get_feature_names_out())

In [376]:
vocab5

33936

In [377]:
vectorizer_6 = CountVectorizer(min_df=10)

matrix_6 = vectorizer_6.fit_transform(texts)

In [378]:
vocab6= len(vectorizer_6.get_feature_names_out())

In [379]:
vocab6

22361

Observation: Increaseing min_df removes rare words from the vocabulary, therefore the vocabulary size decreases.

## Experiment with max_df

In [380]:
vectorizer_7 = CountVectorizer(max_df=1.0)
matrix_7 = vectorizer_7.fit_transform(texts)
len(vectorizer_7.get_feature_names_out())

203208

In [381]:
vectorizer_8 = CountVectorizer(max_df=0.8)
matrix_8 = vectorizer_8.fit_transform(texts)
len(vectorizer_8.get_feature_names_out())

203208

In [382]:
vectorizer_9 = CountVectorizer(max_df=0.5)
matrix_7 = vectorizer_9.fit_transform(texts)
len(vectorizer_9.get_feature_names_out())

203204

### Observation
- max_df removes words that occur in a large percentage of documents. Therefore, decreasing max_df generally decreases the vocabulary size.

# TASK 10

### Question: Difference between One-Hot Encoding and BoW
- One hot encoding represents whether a word is present or basent using 0 and 1
- Bag of words represents how many times a words appear in a document

### Why N-grams increase dimensionality
- N-Grams create combinations of consecutive words. Unigram contain individual words, while bigram and trigram contain two words and three words
- N-Grams create many additional features and increase the vocabulary size

### When to prefer TF-IDF over BoW
- TFIDF is preferred when common words are less useful and want to give more importance to words that are more specific to particular documents
- Bow only considers word frequncy, while TF-IDF also considerss how common a word is across the complete dataset

### Limitations of count based vectorization
- creates a large and sparse vocabulary
- does not understand the menaing of words
- does not understand relationships between words unless N-Grams are used
- synonyms are treated as different words
- require a lot of memory for larger datasets