---
# `N-Grams and TFIDF in Text Vectorization`
---

## `N-Grams ( Bigram, TriGram )`
- In N-grams, rather than taking a unique wordin the vocaulary, we take the sequence of words in the vocabulary.
- In Bigrams, 2 consecutive token ( words) are taken together in the vocabulary
- In Trigrams,  3 consecutive token ( words) are taken together in the vocabulary
- In N-grams, sequential information is maintained

eg.
- Hey I am Arun Jawlia
- I Arun are Jawlia Hey

eg.
- D1:People Love AI

- D2: AI Love AI-ML

- D3: AI-ML Love Love

- D4: Love People People

Bigram Vocabulary
- Bigram [ People Love | Love AI | AI Love | Love AI-ML | AI-ML Love | Love Love | Love People | People People]
- D1: [1,2,0,0,0,0,0,0,0]
- D2: [1,2,0,0,0,0,0,0,0]
- D3: [1,2,0,0,0,0,0,0,0]
- D4: [1,2,0,0,0,0,0,0,0]


Trigram Voculary : [People Love AI | AI Love AI-ML | AI-ML Love Love | Love People People]
- D1 : [ 1, 0, 0, 0]
- D2 : [ 0, 1, 0, 0]
- D3 : [ 0, 0, 1, 0]
- D4 : [ 0, 0, 0, 1]

In a single sentence, max of 3 words

- For the coding parts of n-grams, we are still going to use `CountVectorize` parameter: ngram-range
- ngram-range: ( 1,1) : (minimum, maximum) --: onle single words
- ngram-range: ( 1,2) : min: unigram, max: bigram

In [46]:
import pandas as pd

In [47]:
d = pd.DataFrame({'col':["People Love AI", 'AI Love Data', 'Data Love Love', "Love People People"]})

In [48]:
d

,col
0,People Love AI
1,AI Love Data
2,Data Love Love
3,Love People People


In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv = CountVectorizer()

In [51]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]], dtype=int64)

In [52]:
cv.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

In [53]:
len(cv.vocabulary_)

4

### `Bigram`

In [54]:
cv = CountVectorizer(ngram_range=(2,2))

In [55]:
cv.fit_transform(d['col']).toarray()

array([[0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [56]:
cv.vocabulary_

{'people love': 6,
 'love ai': 2,
 'ai love': 0,
 'love data': 3,
 'data love': 1,
 'love love': 4,
 'love people': 5,
 'people people': 7}

In [57]:
len(cv.vocabulary_)

8

### `Trigram`

In [58]:
cv = CountVectorizer(ngram_range=(3,3))

In [59]:
cv.fit_transform(d['col']).toarray()

array([[0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int64)

In [60]:
cv.vocabulary_

{'people love ai': 3,
 'ai love data': 0,
 'data love love': 1,
 'love people people': 2}

In [61]:
len(cv.vocabulary_)

4

### `Unigram-Bigram`

In [62]:
cv = CountVectorizer(ngram_range=(1,2))

In [63]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1]], dtype=int64)

In [64]:
cv.vocabulary_

{'people': 9,
 'love': 4,
 'ai': 0,
 'people love': 10,
 'love ai': 5,
 'data': 2,
 'ai love': 1,
 'love data': 6,
 'data love': 3,
 'love love': 7,
 'love people': 8,
 'people people': 11}

In [65]:
len(cv.vocabulary_)

12

Note: 
- bigram ---> 8
- unigram---> 4
- trigram --> 4
- unigram + bigram ---> 12

---

N-Gram Properties
1. Sent 1;  this movie is very good
2. Sent 2: this movie is not very good

BoW or Unigram: [This | Movie | is | very | good | Not]
Bigram : [This movie | movie is | is very | very good | is not | not very]
Sent 1: [1,1,1,1,0,0]
Sent 2: [1,1,1,0,1,1]

Difference between Sent 1 and Sent 2 : can be figured out, it is still better than BoW

In terms of Capturing Semantics Relationshis
- Easy to implement
- one issue is that, for large - datasets , vocabulary sizee for unigram ( BoW ) was 4 and for Bigram is 8 
- As you will increase the combination : vocabulary size is going to increase
- This is an issue :computation time is going to increase and training will be difficult
- Wrt out of vocabulary issue ( OOV), New terms are still getting ignored


Next Technique is TFIDF : 

---

## `TFIDF`
- Full Form: Term Frequency Inverse Document Frequency
- It is used for majorly for information retrieval system
- Trying to build: chatbots--> heurisitc methods --> Condition based 

eg. 
- Sent 1: Hello Arun Jawlia
- Vocabulary: [Hello | Arun | Jawlia | is | GenAI]

- In TFIDF , we will see, that if a word in the current document is common in other documents as well as is Rare ?
- In TFIDF, if a word is rare ? too many times appearing in current documents but not frequently repeating in other document 
- word : common --> current doc + other Dock --> TFIDF Score is High
- Score : [Tf * IDF]


Term Frequency : no. of time a word occured in the current doc / total no. of words in the current document
- eg. sent 1: hello arun I am Arun and Hello nice to meet you Arun
- Total Words: 12, 
- TF(Amit) : 3 / 12 --> 1/4
- TF(hello) : 2 / 12 --> 1/6
- 0 <= Term Frequency <= 1  ---> when your word doesn't even occur in the given sentence, every time, the current word iss only occured
- it is more like probability : occurence of given words

Inverse Document Frequency: log(total no. of documents in corpus) / no. of documents with term t in then
- log(total no. of documents in corpus) / no. of documents consisting of that word
- D1: People Love AI
- D2: AI Love AI-ML
- D3: AI-ML Love Love
- D4: Love People People
- People: TF : 1/3, IDF: logn(4/2) --> log(2)
- Love : TF : 1/3, IDF: log(4/4) --> log(0) --> 0


Vocabulary: probability of occurence 

If the word occurs in all sentences or is common then idf = 0
But if a word is rare --> IDF : huge
But if a word is common --> IDF: low


In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
tf = TfidfVectorizer()

In [68]:
tf.fit_transform(d['col'])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (4, 4)>

In [69]:
tf.fit_transform(d['col']).toarray()

array([[0.64043405, 0.        , 0.42389674, 0.64043405],
       [0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.        , 0.60276058, 0.7979221 , 0.        ],
       [0.        , 0.        , 0.31418628, 0.94936136]])

In [70]:
tf.get_feature_names_out()

array(['ai', 'data', 'love', 'people'], dtype=object)

In [71]:
tf.idf_

array([1.51082562, 1.51082562, 1.        , 1.51082562])

In [72]:
tf.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

Properties
1. It is used quite, in information retrieval system 
2. Out of vocabulary : Yes, your words are getting ignored
3. Semantic Relationships
    - S1: This is beautiful
    - S2: This is gorgeous
    - it won't be able to captureing this is that both words have same meaning
4. No semantic relationship capturing capability
   

Custome Features: generate features on my own based on our own domain knowledge
- Complex projects: traditional algo + custom features
- ML : domain knowledge: good custom feature

---
---
# `Complete Notes`
---
---


# `N-Grams and TF-IDF in NLP (Text Vectorization)`

> **N-Grams** and **TF-IDF (Term Frequency–Inverse Document Frequency)** are classical text vectorization techniques that improve upon the limitations of **Bag of Words (BoW)** by preserving local word order (N-Grams) or assigning importance to informative words (TF-IDF).

---

# Recap: Why Do We Need Better Techniques?

Earlier techniques like:

- One-Hot Encoding
- Bag of Words (BoW)

have several limitations:

- Ignore word order
- Ignore context
- Ignore semantic meaning
- Produce sparse vectors
- Suffer from Out-of-Vocabulary (OOV) issues

To overcome some of these limitations, we use:

- N-Grams
- TF-IDF

---

# `N-Grams`

## Definition

An **N-Gram** is a sequence of **N consecutive words (tokens)**.

Unlike Bag of Words, which treats every word independently, N-Grams preserve **local word order**.

> **N = Number of consecutive words**

---

# Types of N-Grams

| N | Name | Example |
|---|------|----------|
| 1 | Unigram | NLP |
| 2 | Bigram | Machine Learning |
| 3 | Trigram | I Love NLP |
| 4 | Four-gram | Deep Learning Model |

---

# Unigram

Each individual word becomes a feature.

Sentence

```text
People Love AI
```

Vocabulary

```text
People

Love

AI
```

This is exactly what **Bag of Words** uses.

---

# Bigram

A Bigram consists of **2 consecutive words**.

Sentence

```text
People Love AI
```

Bigrams

```text
People Love

Love AI
```

---

# Trigram

A Trigram consists of **3 consecutive words**.

Sentence

```text
People Love AI
```

Trigram

```text
People Love AI
```

---

# Example Dataset

Documents

```text
D1 : People Love AI

D2 : AI Love AI-ML

D3 : AI-ML Love Love

D4 : Love People People
```

---

# Bigram Vocabulary

From all documents we create:

```text
People Love

Love AI

AI Love

Love AI-ML

AI-ML Love

Love Love

Love People

People People
```

Vocabulary Size = **8**

---

# Bigram Representation

| Document | People Love | Love AI | AI Love | Love AI-ML | AI-ML Love | Love Love | Love People | People People |
|-----------|------------:|---------:|---------:|------------:|------------:|-----------:|------------:|---------------:|
| D1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 |
| D2 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 |
| D3 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 0 |
| D4 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 1 |

Notice that the **sequence of words is preserved**, unlike Bag of Words.

---

# Trigram Vocabulary

Vocabulary

```text
People Love AI

AI Love AI-ML

AI-ML Love Love

Love People People
```

---

# Trigram Representation

| Document | People Love AI | AI Love AI-ML | AI-ML Love Love | Love People People |
|-----------|---------------:|--------------:|----------------:|-------------------:|
| D1 | 1 | 0 | 0 | 0 |
| D2 | 0 | 1 | 0 | 0 |
| D3 | 0 | 0 | 1 | 0 |
| D4 | 0 | 0 | 0 | 1 |

---

# Using CountVectorizer

Scikit-learn provides **CountVectorizer** for both Bag of Words and N-Grams.

```python
CountVectorizer(ngram_range=(1,1))
```

Only Unigrams

---

```python
CountVectorizer(ngram_range=(1,2))
```

Unigrams + Bigrams

---

```python
CountVectorizer(ngram_range=(2,2))
```

Only Bigrams

---

```python
CountVectorizer(ngram_range=(3,3))
```

Only Trigrams

---

# `Why N-Grams are Better than BoW`

Consider two sentences:

Sentence 1

```text
This movie is very good.
```

Sentence 2

```text
This movie is not very good.
```

---

## Bag of Words

Vocabulary

```text
This

Movie

Is

Very

Good

Not
```

Both sentences contain almost the same words.

The vectors are very similar.

BoW struggles to distinguish the different meanings.

---

## Bigram Representation

Sentence 1

```text
This movie

movie is

is very

very good
```

Sentence 2

```text
This movie

movie is

is not

not very

very good
```

Now the phrase:

```text
is not
```

appears only in Sentence 2.

Therefore,

Bigrams can better distinguish the two sentences.

---

# Advantages of N-Grams

- Preserves local word order.
- Better than BoW for short phrases.
- Captures simple context.
- Easy to implement.
- Works well for search and document classification.

---

# Limitations of N-Grams

## 1. Vocabulary Explosion

As N increases,

Vocabulary size grows rapidly.

Example

Vocabulary

```text
10000 words
```

Possible Bigrams

↓

Much larger

Possible Trigrams

↓

Even larger

This increases:

- Memory usage
- Training time
- Computational cost

---

## 2. Sparse Vectors

Most N-Grams do not appear in every document.

Therefore,

the vectors remain sparse.

---

## 3. Out-of-Vocabulary (OOV)

If a new word or phrase appears during testing,

it cannot be represented.

---

## 4. Limited Semantic Understanding

Sentence

```text
This is beautiful.
```

Sentence

```text
This is gorgeous.
```

N-Grams treat

Beautiful

and

Gorgeous

as different words.

No semantic similarity is learned.

---

# `TF-IDF (Term Frequency–Inverse Document Frequency)`

## Definition

TF-IDF is a statistical technique that measures **how important a word is in a document relative to the entire corpus**.

Unlike Bag of Words, which only counts word frequency,

TF-IDF reduces the importance of common words and increases the importance of rare but informative words.

---

# Why Do We Need TF-IDF?

Consider these words:

```text
the

is

and
```

They appear in almost every document.

Although frequent,

they are not useful for distinguishing documents.

TF-IDF gives such words **lower weights**.

---

Words like:

```text
Cancer

Transformer

Quantum
```

may appear in only a few documents.

These are highly informative.

TF-IDF assigns them **higher weights**.

---

# TF-IDF Formula

```text
TF-IDF = TF × IDF
```

---

# `Term Frequency (TF)`

## Definition

Term Frequency measures how often a word appears **within the current document**.

Formula

```text
TF =

(Number of occurrences of the word)

/

(Total number of words in the document)
```

---

## Example

Sentence

```text
Hello Arun

I am Arun

Nice to meet you Arun

Hello
```

Suppose

Total Words = 12

Occurrences

Arun = 3

Hello = 2

Then

```text
TF(Arun)

=

3/12

=

0.25
```

```text
TF(Hello)

=

2/12

=

0.166
```

Higher TF means

the word is more important **within that document**.

---

# `Inverse Document Frequency (IDF)`

## Definition

IDF measures **how rare or unique a word is across the entire corpus**.

Formula

```text
IDF

=

log

(

Total Documents

/

Documents containing the word

)
```

In practice, libraries such as scikit-learn use a **smoothed version** of this formula to avoid division by zero.

---

# Example

Documents

```text
D1

People Love AI

D2

AI Love AI-ML

D3

AI-ML Love Love

D4

Love People People
```

Total Documents

```text
N = 4
```

---

### Word = Love

Appears in

D1

D2

D3

D4

Document Frequency

```text
DF = 4
```

IDF

```text
log(4/4)

=

log(1)

=

0
```

Love receives a very low weight because it appears everywhere.

---

### Word = People

Appears in

D1

D4

Document Frequency

```text
DF = 2
```

IDF

```text
log(4/2)

=

log(2)

≈ 0.693
```

Higher than "Love"

because it is rarer.

---

# Final TF-IDF Score

```text
TF-IDF

=

TF × IDF
```

Words that:

- appear frequently in one document
- but rarely in the corpus

receive the highest scores.

---

# Applications of TF-IDF

TF-IDF is widely used in:

- Search Engines
- Information Retrieval
- Document Ranking
- Spam Detection
- Document Classification
- News Categorization
- Keyword Extraction

---

# Advantages of TF-IDF

- Better than Bag of Words.
- Reduces the importance of common words.
- Highlights informative words.
- Easy to compute.
- Works well with classical ML algorithms.

---

# `Limitations of TF-IDF`

## 1. No Semantic Meaning

Sentence 1

```text
This is beautiful.
```

Sentence 2

```text
This is gorgeous.
```

TF-IDF treats

Beautiful

and

Gorgeous

as completely unrelated.

---

## 2. Ignores Word Order

Sentence

```text
Dog bites man
```

Sentence

```text
Man bites dog
```

The order is ignored.

---

## 3. OOV Problem

New words that were not present during training cannot be represented.

---

## 4. Sparse Representation

Like BoW,

TF-IDF produces sparse vectors.

---

# `Custom Features`

## Definition

Custom Features are manually designed numerical features based on domain knowledge.

Example (Sentiment Analysis)

Sentence

```text
I absolutely love this phone!!!
```

Possible custom features:

- Number of positive words
- Number of negative words
- Number of exclamation marks
- Sentence length
- Emoji count
- Capital letters count

These features are often combined with:

- TF-IDF
- N-Grams
- Classical ML algorithms

to improve performance.

---

# `N-Grams vs TF-IDF`

| Feature | N-Grams | TF-IDF |
|----------|----------|---------|
| Preserves Word Order | ✅ | ❌ |
| Uses Word Frequency | ✅ | ✅ |
| Gives Importance to Rare Words | ❌ | ✅ |
| Sparse Representation | ✅ | ✅ |
| Captures Semantic Meaning | ❌ | ❌ |
| OOV Problem | ✅ | ✅ |
| Best For | Local Context | Information Retrieval & Text Classification |

---

# `Why Modern NLP Moved Beyond TF-IDF`

Although N-Grams and TF-IDF improved over Bag of Words,

they still cannot understand:

- Context
- Semantics
- Synonyms
- Polysemy
- Long-range dependencies

This led to embedding-based methods:

- Word2Vec
- FastText
- GloVe
- BERT
- GPT
- Sentence Transformers

These methods learn dense vectors that preserve semantic relationships.

---

# `Interview Tips`

✅ N-Grams preserve local word order.

✅ Bigrams consist of two consecutive words; Trigrams consist of three consecutive words.

✅ TF-IDF assigns higher weights to words that are frequent in a document but rare across the corpus.

✅ TF-IDF is widely used in search engines and information retrieval.

✅ Neither N-Grams nor TF-IDF captures true semantic meaning.

---

# `Key Takeaways`

- N-Grams improve upon Bag of Words by preserving short word sequences.
- TF-IDF improves upon Bag of Words by weighting informative words more highly than common words.
- Both techniques still produce sparse vectors and do not capture semantic relationships.
- Modern NLP systems rely on dense embeddings and Transformer-based models to overcome these limitations.

---

# `2. Interview Questions & Answers`

## Beginner Questions

**1. What is an N-Gram?**
An N-Gram is a sequence of **N consecutive words** used as a feature in text representation.

**2. What is the difference between Unigram, Bigram, and Trigram?**

* Unigram → 1 word
* Bigram → 2 consecutive words
* Trigram → 3 consecutive words

---

**3. What is TF-IDF?**
TF-IDF (Term Frequency–Inverse Document Frequency) measures how important a word is within a document relative to the entire corpus.

---

## Intermediate Questions

**4. Why is TF-IDF better than Bag of Words?**
Because TF-IDF reduces the weight of common words (e.g., "the", "is") and increases the weight of rare but informative words.

**5. Why does vocabulary size increase in N-Grams?**
As we combine consecutive words, the number of possible combinations grows rapidly, increasing the vocabulary size and computational cost.

---

## Scenario-Based Questions

**Q1. You're building a search engine for research papers. Would you choose BoW or TF-IDF? Why?**
**Answer:** TF-IDF, because it highlights rare and informative terms, making document retrieval and ranking more effective.

**Q2. Two sentences differ only by the word "not". Which technique better distinguishes them: BoW or Bigrams?**
**Answer:** Bigrams, because phrases like **"is not"** are treated as unique features, preserving local word order and improving distinction.

---

# `3. 30-Second Revision`

* **N-Grams** preserve local word sequences (Unigram, Bigram, Trigram).
* **TF-IDF** = TF × IDF.
* **TF** measures word importance within a document.
* **IDF** measures how rare a word is across the corpus.
* Both still produce sparse vectors and do not understand semantic meaning.

---

# `4. 2-Minute Revision`

* N-Grams extend BoW by capturing short sequences of words.
* As **N** increases, vocabulary size and computational cost also increase.
* TF-IDF assigns high scores to words that are common in one document but rare across the corpus.
* TF-IDF is widely used in search engines, information retrieval, and document classification.
* Neither N-Grams nor TF-IDF understands synonyms, context, or long-range dependencies, which is why modern NLP uses embedding-based techniques such as Word2Vec and Transformers.

---
