# `NumPy Attributes`
---

In [42]:
import numpy as np

## 1. `ndim`
- ndim stands for n dimesions
- Returns number of dimensions

In [43]:
one_darray = np.array([1,2,3,4,5])
print(one_darray.ndim)

1


In [44]:
two_darray = np.array([[1,2,3],[5,6,7]])
print(two_darray.ndim)

2


In [45]:
three_darray = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]])
three_darray.ndim

3

## 2. `shape` : 
- provide the idea about the rows, and column in our dataset or in array
- Returns dimensions of array.

In [46]:
one_darray = np.array([1,2,3,4,5]) 
print(one_darray.shape)

(5,)


In [47]:
two_darray = np.array([[1,2,3],[5,6,7]])
print(two_darray.shape)

(2, 3)


In [48]:
three_darray = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]]) #
print(three_darray.shape) # row, col, z-axis ==> 2, 2 ,3

(2, 2, 3)


## 3. `size`: 
- returns total number of elements present inside our dataset or Array

In [49]:
array_elements = np.arange(5,57)
print(array_elements.size)

52


## 4. `itemsize`: 
- provides with the idea about the size of a unique element inside our array in bytes
- Returns size of one element in bytes.

In [50]:
print(np.array([[1,2], [3,4], [5,6]]).itemsize) # 8 byte
print(np.array([[1, 2, 10], [3, 4, 20], [5, 6, 40]]).itemsize) # 8 byte

8
8


In [51]:
print(np.array([[1, 2, 10], [3, 4, 20], [5, 6, 40]], dtype=np.int32).itemsize) # 4 byte - consuming less memory

4


## 5. `dtype`: 
- provides us with the idea about the type of every item inside an array

In [52]:
np.array([[1,2,3], [4,5,6]]).dtype # every item store up to 8 bytes

dtype('int64')

## 6. `astype()`
- Converts datatype
- will be helping us out with figuring out the data type of the column in the dataset in panda and it will be used in numpy as well for getting the datatype changed of our overal array.

In [53]:
arr = np.array([13,4,4,5])
arr = arr.astype(float)
print(arr)

[13.  4.  4.  5.]


In [54]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8, 9]])
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
print(type(arr2))
print(arr2.dtype)
arr = arr2.astype('float64')
print(arr)
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>
float64


## 6. `nbytes`

One of the most important memory-related attributes.

Returns total memory consumed by the array.

In [56]:
arr = np.array([1,2,3,4])

print(arr.nbytes) # 32

# 4 elements × 8 bytes = 32 bytes
# Relationship: nbytes = size × itemsize

32


## 8. `T`

- Returns transpose.
- Syntax: arr.T

In [57]:
arr = np.arange(6).reshape(2,3)
print(arr)

print(arr.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


## 9. `real`

Returns real part.


In [58]:
arr = np.arange(6).reshape(2,3)
arr.real
# Useful for complex numbers.

array([[0, 1, 2],
       [3, 4, 5]])

## 10. `imag`

Returns imaginary part.

In [59]:
arr = np.array([2+3j,4+5j])

print(arr.imag)

[3. 5.]


## 11. `flat`

Iterator over all elements.

In [60]:
for i in arr.flat:
    print(i)

(2+3j)
(4+5j)


## 12. `flags`

Memory layout information.

In [61]:
arr.flags

# Useful in optimization.

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

## 13. `strides`

Shows memory jump between elements.

In [62]:
arr.strides

# Very useful for understanding NumPy internals.

(16,)

# Useful Array Methods

These aren't attributes but belong in the same chapter because they're commonly used with arrays.

---

## `copy()`

```python
arr.copy()
```

---

## `view()`

```python
arr.view()
```

Difference between shallow and deep copy.

---



## `reshape()`

```python
arr.reshape(3,4)
```

---

## `flatten()`

```python
arr.flatten()
```

Returns a copy.

---


## `ravel()`

```python
arr.ravel()
```

Returns a view whenever possible.

---

## `transpose()`

```python
arr.transpose()
```

Equivalent to

```python
arr.T
```

---


## `tolist()`

Convert NumPy array to Python list.

```python
arr.tolist()
```

---


## `byteswap()`

Changes byte order.

Mostly useful in advanced applications.

---


# Memory-related Attributes

| Attribute  | Meaning            |
| ---------- | ------------------ |
| `itemsize` | Bytes per element  |
| `size`     | Number of elements |
| `nbytes`   | Total memory used  |
| `dtype`    | Data type          |

Remember this formula:

```text
nbytes = size × itemsize
```

---

# Shape-related Attributes

| Attribute | Meaning              |
| --------- | -------------------- |
| `ndim`    | Number of dimensions |
| `shape`   | Shape of array       |
| `size`    | Total elements       |

---


# `Complete NumPy Array Attributes Roadmap`

### Basic Attributes

* ✅ `ndim`
* ✅ `shape`
* ✅ `size`
* ✅ `dtype`
* ✅ `itemsize`
* ⭐ `nbytes`

### Matrix-related

* ⭐ `T`
* ⭐ `transpose()`

### Datatype

* ✅ `astype()`

### Memory

* ⭐ `flags`
* ⭐ `strides`

### Complex Numbers

* ⭐ `real`
* ⭐ `imag`

### Iteration

* ⭐ `flat`

### Conversion

* ⭐ `tolist()`

### Copying

* ⭐ `copy()`
* ⭐ `view()`

### Shape Manipulation

* ⭐ `reshape()`
* ⭐ `flatten()`
* ⭐ `ravel()`

### Recommendation

If this is your **"NumPy Attributes"** chapter, focus on the **attributes** (`ndim`, `shape`, `size`, `dtype`, `itemsize`, `nbytes`, `T`, `real`, `imag`, `flat`, `flags`, `strides`) and briefly mention methods like `astype()` and `reshape()` in a separate **"Array Methods"** chapter. This keeps the distinction clear:

* **Attributes**: Accessed without parentheses (e.g., `arr.shape`, `arr.dtype`).
* **Methods**: Called with parentheses (e.g., `arr.astype()`, `arr.reshape()`).
