# `Mathematical Operations in Numpy`
---

In [1]:
import numpy as np

## Scalar Operations: 
- A scalar value wiht be multiplied with the array or a numerice value  ( eg 1, 4 )

In [2]:
arr = np.random.random((3,3))*100

print(arr)

[[87.24873357 45.26989005 55.02786476]
 [50.09734619 28.30944821 58.33712002]
 [12.46198984 19.02942899 21.94099278]]


In [3]:
new_arr = np.round(arr).astype('int32')
print(new_arr)

[[87 45 55]
 [50 28 58]
 [12 19 22]]


In [4]:
# Scalar Operations with Our Matrix or Array

addition_operation = new_arr + 15 # Addition 
print("Add", addition_operation)

print('\n')

substract_operation = new_arr - 5 # substract 5 from all the value of matrix
print(substract_operation)

print('\n')

multiplication_operation = new_arr * 5 # multiplication 5 from all the value of matrix
print(multiplication_operation)

print('\n')

division_operation = new_arr / 5 # division 5 from all the value of matrix
print(division_operation)


Add [[102  60  70]
 [ 65  43  73]
 [ 27  34  37]]


[[82 40 50]
 [45 23 53]
 [ 7 14 17]]


[[435 225 275]
 [250 140 290]
 [ 60  95 110]]


[[17.4  9.  11. ]
 [10.   5.6 11.6]
 [ 2.4  3.8  4.4]]


In [5]:
# We can appply scalar operation with the array in terms of arithmetic operations

In [6]:
arr = np.random.random((3,3))*100

print(arr > 50)
print("\n")
print(arr < 50)

[[False False  True]
 [False  True  True]
 [ True False False]]


[[ True  True False]
 [ True False False]
 [False  True  True]]


In [7]:
# Vector Operations - Operations will be in between the given numbers of matrices

arr_1 = np.arange(1,17).reshape(4,4)
arr_2 = np.arange(17,33).reshape(4,4)

print(arr_1)
print("\n")
print(arr_2)
print("\n Addition")
print(arr_1 + arr_2)
print("\n Substraction")
print(arr_1 - arr_2)
print("\n Multiplication")
print(arr_1 * arr_2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

 Addition
[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]

 Substraction
[[-16 -16 -16 -16]
 [-16 -16 -16 -16]
 [-16 -16 -16 -16]
 [-16 -16 -16 -16]]

 Multiplication
[[ 17  36  57  80]
 [105 132 161 192]
 [225 260 297 336]
 [377 420 465 512]]


## Important Functions in NumPy for Machine Learning and DAta Science

1. `max()`
   - To calculate the max value inside a Matrix or an Array
   - Syntax: `np.max(array)`

In [8]:
arr = np.arange(1,10)
print(np.max(arr))

9


In [9]:
max_arr = np.arange(1,17).reshape(4,4) 
print(np.max(max_arr)) # from the matrix


16


In [10]:
max_arr = np.round(np.random.random((4,4))*100).astype('int32')
print(max_arr)
print(np.max(max_arr))


[[80 74  2  9]
 [57 27 40 10]
 [18 53 37 65]
 [94 28 86  7]]
94


axis --> provide us with the idea about any operation value inside a specific row or column or we can get a specific value row wise or column wise

axix =  0 --> column wise operation
axix =  1 --> row wise operation

In [11]:
print(np.max(max_arr, axis = 0)) # max from columns
print("\n")
print(np.max(max_arr, axis = 1)) # max from rows

[94 74 86 65]


[80 57 65 94]


## 2. `min()`
- used for calculating the minimum value for the Matrix or an Array
- Syntax: `np.min(array)`

In [12]:
arr = np.arange(1,10)
print(np.min(arr))

1


In [13]:
min_arr = np.round(np.random.random((3,3))*100).astype("int32")
print(min_arr)
print("Minimum of matrix", np.min(min_arr))

[[13 85  8]
 [35 27 85]
 [ 2 48 86]]
Minimum of matrix 2


In [14]:
print(np.min(min_arr, axis = 0)) # min from columns
print("\n")
print(np.min(min_arr, axis = 1)) # min from rows

[ 2 27  8]


[ 8 27  2]


## 3. `sum()`
- calculates the sum of all of the values of a given matrix
- Syntax: np.sum(arr)

In [15]:
sum_arr = np.arange(1,20).sum()
print(sum_arr)

190


In [16]:
min_matrix = np.round(np.random.random((3,3))*100).astype("int32")
print(min_matrix)
print(np.sum(min_matrix))

[[ 2  6 69]
 [32 27 46]
 [90 11 64]]
347


In [17]:
sum_matrix_row = np.round(np.random.random((3,3))*100).astype("int32") # row
print(sum_matrix_row)
print(np.sum(sum_matrix_row, axis = 1))

[[53 73 41]
 [37 92 49]
 [65 39 90]]
[167 178 194]


In [18]:
sum_matrix_col = np.round(np.random.random((3,3))*100).astype("int32") # column
print(sum_matrix_col)
print(np.sum(sum_matrix_col, axis = 0))

[[96 11 17]
 [95 80 85]
 [52 44 78]]
[243 135 180]


## 4. `prod()`
- calculating the product of all values inside the array or matrix
- Syntax: `np.prod(arr)`

In [19]:
arr = np.arange(1,10)
print(np.prod(arr))

362880


In [20]:
prod_matrix = np.round(np.random.random((3,3))*100).astype("int32") 
print(prod_matrix)
print('\n')
print(np.prod(prod_matrix))

[[85 68 43]
 [88 57 55]
 [70 72  6]]


-183907328


In [21]:
prod_matrix = np.round(np.random.random((3,3))*100).astype("int32") 
print(prod_matrix)
print('\n')
print(np.prod(prod_matrix))
print('\n')
print(np.prod(prod_matrix, axis = 0)) # column wise product
print('\n')
print(np.prod(prod_matrix, axis = 1)) # row wise product

[[18 38 97]
 [74 27 92]
 [75  4  2]]


-1129891584


[99900  4104 17848]


[ 66348 183816    600]
