# `NumPy Statistical Functions`
---

In [1]:
import numpy as np

## 1. `mean()`
- mean of all values inside the array and matrix
- Syntax: np.mean()

In [2]:
arr = np.arange(1,20)
print("mean", np.mean(arr))

mean 10.0


In [3]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Mean of Matrix: ", np.mean(mat))
print("\n")
print("Mean of Columns: ", np.mean(mat, axis= 0))
print("\n")
print("Mean of Rows: ", np.mean(mat, axis = 1))

[[37 59 34 27]
 [10 38 92 74]
 [79 54  7 93]
 [11 79 43 31]]


Mean of Matrix:  48.0


Mean of Columns:  [34.25 57.5  44.   56.25]


Mean of Rows:  [39.25 53.5  58.25 41.  ]


## 2. `std()`
- provides with the standard deviation of all valeus of the matrix or array
- Syntax: np.std(arr)

In [4]:
arr = np.arange(1,20)
print("Standard Deviation", np.std(arr))

Standard Deviation 5.477225575051661


In [5]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Standard Deviation of Matrix: ", np.std(mat))
print("\n")
print("Standard Deviation of Columns: ", np.std(mat, axis= 0))
print("\n")
print("Standard Deviation of Rows: ", np.std(mat, axis = 1))

[[69 80 24 80]
 [19 34 43 70]
 [32 39 22 29]
 [31 65 12 60]]


Standard Deviation of Matrix:  22.058781556332615


Standard Deviation of Columns:  [18.75333304 18.84807682 11.21104366 19.10987964]


Standard Deviation of Rows:  [23.10167743 18.55397532  6.10327781 21.64486082]


## 3. `median()`
- help us out calculate the Median of all values in the Array or Matrix
- Syntax: `np.median(arr)`

In [6]:
arr = np.arange(1,20)
print("Median of an array: ", np.median(arr))

Median of an array:  10.0


In [7]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Median of Matrix: ", np.median(mat))
print("\n")
print("Median of Columns: ", np.median(mat, axis= 0))
print("\n")
print("Median of Rows: ", np.median(mat, axis = 1))

[[ 35  79   7  69]
 [ 33  69  20  60]
 [ 64  59  92  23]
 [100  43  65  24]]


Median of Matrix:  59.5


Median of Columns:  [49.5 64.  42.5 42. ]


Median of Rows:  [52.  46.5 61.5 54. ]


## 4. `var()`
- calculating the variance of all values inside the array or matrix
- Syntax: np.var()

In [8]:
arr = np.arange(1,20)
print("Variance of an array: ", np.median(arr))

Variance of an array:  10.0


In [9]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Variance of Matrix: ", np.var(mat))
print("\n")
print("Variance of Columns: ", np.var(mat, axis= 0))
print("\n")
print("Variance of Rows: ", np.var(mat, axis = 1))

[[ 11  68  71  60]
 [ 26  16  55  64]
 [100  57  79  57]
 [ 66  22  86  19]]


Variance of Matrix:  679.49609375


Variance of Columns:  [1212.6875  492.6875  133.1875  326.5   ]


Variance of Rows:  [590.25   393.1875 319.1875 821.1875]


# `Trigonometric Functions in NumPy`
---

## 1. `sin()`
- sin value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [10]:
np.sin(30)

-0.9880316240928618

## 2. `cos()`
- cos value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [11]:
np.cos(30)

0.15425144988758405

## 2. `tan()`
- tan value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [12]:
np.tan(30)

-6.405331196646276

# `DOT Product of Matrix`
---

- No of rows of first matrix is equal to the no. of columns of second matrix
- Syntax: np.dot(matrix1, matrix2)

In [13]:
mat_1 = np.round(np.random.random((3,4))*100).astype('int32')
mat_2 = np.round(np.random.random((4,3))*100).astype('int32')

print("Mat 1", mat_1)
print("\n")
print("Mat 2", mat_2)
print("\n")
print(np.dot(mat_1,mat_2))

Mat 1 [[85 95 81 42]
 [68 79 12 14]
 [74 73  9 14]]


Mat 2 [[82 13 56]
 [ 7 33 30]
 [ 6 54 50]
 [25  3 75]]


[[ 9171  8740 14810]
 [ 6551  4181  7828]
 [ 6983  3899  7834]]


In [14]:
mat_1 = np.round(np.random.random((3,5))*100).astype('int32')
mat_2 = np.round(np.random.random((4,3))*100).astype('int32')

# print(np.dot(mat_1,mat_2)) # ValueError: shapes (3,5) and (4,3) not aligned: 5 (dim 1) != 4 (dim 0)

## `log()`
- to calculate the log of all values of our Matrix

In [15]:
mat_1 = np.round(np.random.random((3,5))*100).astype('int32')
print(np.log(mat_1))

[[3.63758616 3.52636052 4.18965474 2.89037176 4.49980967]
 [3.58351894 2.89037176 4.26267988 4.34380542 4.47733681]
 [3.09104245 2.99573227 4.06044301 4.36944785 2.89037176]]


# `exp()`:
- exponential of all values inside the Matrix
- Syntax: np.exp()

In [16]:
mat = np.round(np.random.random((3,5))*100).astype('int32')

print(np.exp(mat))

[[1.54553894e+25 7.20048993e+10 5.83461743e+14 2.51543867e+30
  2.29378316e+27]
 [6.07603023e+37 1.14200739e+26 3.02507732e+36 9.49611942e+19
  3.18559318e+16]
 [2.83075330e+23 1.69488924e+28 6.07603023e+37 2.45124554e+40
  4.85165195e+08]]


## `round()`
- helps us rounding off the float values to its nearest possible integer value
- Syntax: np.round()

eg.
- if values is 1.4 --> round off is 0.0
- if values is 1.5 --> round off is 0.0
- if values is 1.6 --> round off is 2.0

In [17]:
print(np.round(1.4))
print(np.round(1.5))
print(np.round(1.6))

1.0
2.0
2.0


In [18]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.round(mat))

[[8.27726867 7.09972629 3.57315805 3.36564325]
 [5.33738955 8.38741993 5.307698   8.34896095]
 [5.90894829 4.02688442 1.3135692  8.61770592]]


[[8. 7. 4. 3.]
 [5. 8. 5. 8.]
 [6. 4. 1. 9.]]


## `ceil()`
- helps us rounding off the float values to its next max value ( corresponding value )
- Syntax: np.ceil()

eg.
- if values is 1.4 --> ceil value is 2.0
- if values is 1.5 --> ceil value is 2.0
- if values is 1.6 --> ceil value is 2.0

In [19]:
print(np.ceil(1.4))
print(np.ceil(1.5))
print(np.ceil(1.6))

2.0
2.0
2.0


In [20]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.ceil(mat))

[[5.16297476 2.74430361 8.76112923 6.02860682]
 [2.85117863 2.6544546  9.66579858 3.02811534]
 [1.27362544 1.61863002 1.1541057  1.33723859]]


[[ 6.  3.  9.  7.]
 [ 3.  3. 10.  4.]
 [ 2.  2.  2.  2.]]


## `floor()`
- helps us rounding off the float values to its nearest minimum value
- Syntax: `np.floor()`

eg.
- if values is 1.4 --> floor value is 1.0
- if values is 1.5 --> floor value is 1.0
- if values is 1.9 --> floor value is 1.0

In [21]:
print(np.floor(1.4))
print(np.floor(1.5))
print(np.floor(1.6))

1.0
1.0
1.0


In [22]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.floor(mat))

[[1.31621633 3.00682214 2.6210743  0.65093358]
 [5.95306813 6.90704505 2.85106962 3.86205702]
 [5.42523259 3.05198712 7.99696299 2.56645642]]


[[1. 3. 2. 0.]
 [5. 6. 2. 3.]
 [5. 3. 7. 2.]]


## `transpose()`
- rotate the matrix
- Syntax : `np.transpose(arr)` or `arr.T`

In [23]:
mat = np.round(np.random.random((3,4))*100).astype('int32')
print(mat)
print("\n Transpose Matrix")
print(np.transpose(mat))

[[13 56 35 68]
 [15 98 36 49]
 [97 72  9 99]]

 Transpose Matrix
[[13 15 97]
 [56 98 72]
 [35 36  9]
 [68 49 99]]


In [24]:
mat = np.arange(1,13).reshape(3,4)
print(mat)
print("\n Transpose Matrix")
print(np.transpose(mat))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Transpose Matrix
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## `Ravel()`
- used to convert ndarray into 1darray
- Syntax: `np.ravel(arr)`

In [35]:
mat = np.arange(1,13).reshape(3,4)
print("dimension", mat.ndim)

print("\n")

new_mat = np.ravel(mat)
print("dimension", new_mat.ndim)

dimension 2


dimension 1


## Important Functions

## `Indexing and Slicing in NumPy`

Indexing --> lists[,size-1] --> to have the access over the value

In [26]:
one_darray = np.arange(1,15)
print(one_darray)
print(one_darray[0])
print(one_darray[2])
print(one_darray[2])
print(one_darray[-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1
3
3
14


In [27]:
two_darray = np.round(np.random.random((5,5))*100).astype("int32")
print(two_darray)
print('\n col')
print(two_darray[0])


[[77 80 24 96 10]
 [23 84 19 94 18]
 [36 68  9 57  8]
 [14 86  1 88 99]
 [37 22 25 76 66]]

 col
[77 80 24 96 10]


In [28]:
print(two_darray[0,0])
print(two_darray[4,4])
# two_darray[5,5]IndexError: index 5 is out of bounds for axis 0 with size 5

77
66


In [29]:
three_darray = np.arange(1,9).reshape(2,2,2)
print(three_darray)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
three_darray = np.array([[[1,2,3],[4,5,6]], [[11,12,13],[14,15,16]], [[21,22,23],[24,25,26]]])
print(three_darray)
print(three_darray[0,1,2])
print(three_darray[2,1,1])
# Indexing --> [z-axis, x-axis, y-axis]
# Indexing --> [z-axis, row, col]

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
6
25


## `Slicing`
- similar approach just like the lists
- 2D array : [row : row_2, col_1: col_2]

In [31]:
two_darray = np.arange(1,17).reshape(4,4)
print(two_darray)
print(two_darray[:,2])
print("---")
print(two_darray[0,:])
print("---")
print(two_darray[2:4])
print("---")
print(two_darray[2:4, 3:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 3  7 11 15]
---
[1 2 3 4]
---
[[ 9 10 11 12]
 [13 14 15 16]]
---
[[12]
 [16]]


In [32]:
print(two_darray[1:3]) # row 1 to 3 so row 1 and 2 print
print(two_darray[1:3, 1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


## `Iterateing over an Array`

In [33]:
array = np.arange(1,10)

for i in array:
    print(i)


1
2
3
4
5
6
7
8
9


In [34]:
array = np.arange(1,10).reshape(3,3)
print(array)

for i in array:
    for j in array:
        print(array[i][j])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
array = np.arange(1,28).reshape(3,3,3)
# print(array)

for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


## `nditer()`: n dimension iterate function
- help us out with iterating over every value in a nd array
- Synatx: np.nditer()


1D array --> value by value on iteration

2D array --> row by row on iteration

3D array --> 2d array by 2d array

In [ ]:
array = np.arange(1,28).reshape(3,3,3)

for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


## `Stacking and Splitting`

### `Stacking`: joining the Arrays Together
- Horizontal Stacking: Row By Row Joining is done
  - Syntax: `np.hstack()`
- Vertical Stacking: Column By Column Joining is done
  - Syntax: `np.vstack()` 

Note: Size of Arrays must be same

In [ ]:
mat_1 = np.arange(1,13).reshape(3,4)
mat_2 = np.arange(13,25).reshape(3,4)

print(mat_1)
print(mat_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
horizontal_stacking = np.hstack((mat_1, mat_2))
print(horizontal_stacking)

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
24


In [ ]:
vertical_stacking = np.vstack((mat_1, mat_2))
print(vertical_stacking)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


## `Splitting`
- Horizontal Split --> np.hsplit(arr, number of parts you want to be splitted at)
- Vertical Split --> np.vsplit(arr, number of parts)

In [ ]:
print("Original Array")
print(vertical_stacking)
np.hsplit(vertical_stacking,2)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [ ]:
print("Original Array")
print(vertical_stacking)
print(np.vsplit(vertical_stacking,2))

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
