# `NumPy Statistical Functions`
---

In [ ]:
import numpy as np

## 1. `mean()`
- mean of all values inside the array and matrix
- Syntax: np.mean()

In [ ]:
arr = np.arange(1,20)
print("mean", np.mean(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Mean of Matrix: ", np.mean(mat))
print("\n")
print("Mean of Columns: ", np.mean(mat, axis= 0))
print("\n")
print("Mean of Rows: ", np.mean(mat, axis = 1))

## 2. `std()`
- provides with the standard deviation of all valeus of the matrix or array
- Syntax: np.std(arr)

In [ ]:
arr = np.arange(1,20)
print("Standard Deviation", np.std(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Standard Deviation of Matrix: ", np.std(mat))
print("\n")
print("Standard Deviation of Columns: ", np.std(mat, axis= 0))
print("\n")
print("Standard Deviation of Rows: ", np.std(mat, axis = 1))

## 3. `median()`
- help us out calculate the Median of all values in the Array or Matrix
- Syntax: `np.median(arr)`

In [ ]:
arr = np.arange(1,20)
print("Median of an array: ", np.median(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Median of Matrix: ", np.median(mat))
print("\n")
print("Median of Columns: ", np.median(mat, axis= 0))
print("\n")
print("Median of Rows: ", np.median(mat, axis = 1))

## 4. `var()`
- calculating the variance of all values inside the array or matrix
- Syntax: np.var()

In [ ]:
arr = np.arange(1,20)
print("Variance of an array: ", np.median(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Variance of Matrix: ", np.var(mat))
print("\n")
print("Variance of Columns: ", np.var(mat, axis= 0))
print("\n")
print("Variance of Rows: ", np.var(mat, axis = 1))

# `Trigonometric Functions in NumPy`
---

## 1. `sin()`
- sin value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [ ]:
np.sin(30)

## 2. `cos()`
- cos value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [ ]:
np.cos(30)

## 2. `tan()`
- tan value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [ ]:
np.tan(30)

# `DOT Product of Matrix`
---

- No of rows of first matrix is equal to the no. of columns of second matrix
- Syntax: np.dot(matrix1, matrix2)

In [ ]:
mat_1 = np.round(np.random.random((3,4))*100).astype('int32')
mat_2 = np.round(np.random.random((4,3))*100).astype('int32')

print("Mat 1", mat_1)
print("\n")
print("Mat 2", mat_2)
print("\n")
print(np.dot(mat_1,mat_2))

In [ ]:
mat_1 = np.round(np.random.random((3,5))*100).astype('int32')
mat_2 = np.round(np.random.random((4,3))*100).astype('int32')

# print(np.dot(mat_1,mat_2)) # ValueError: shapes (3,5) and (4,3) not aligned: 5 (dim 1) != 4 (dim 0)

## `log()`
- to calculate the log of all values of our Matrix

In [ ]:
mat_1 = np.round(np.random.random((3,5))*100).astype('int32')
print(np.log(mat_1))

# `exp()`:
- exponential of all values inside the Matrix
- Syntax: np.exp()

In [ ]:
mat = np.round(np.random.random((3,5))*100).astype('int32')

print(np.exp(mat))

## `round()`
- helps us rounding off the float values to its nearest possible integer value
- Syntax: np.round()

eg.
- if values is 1.4 --> round off is 0.0
- if values is 1.5 --> round off is 0.0
- if values is 1.6 --> round off is 2.0

In [ ]:
print(np.round(1.4))
print(np.round(1.5))
print(np.round(1.6))

In [ ]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.round(mat))

## `ceil()`
- helps us rounding off the float values to its next max value ( corresponding value )
- Syntax: np.ceil()

eg.
- if values is 1.4 --> ceil value is 2.0
- if values is 1.5 --> ceil value is 2.0
- if values is 1.6 --> ceil value is 2.0

In [ ]:
print(np.ceil(1.4))
print(np.ceil(1.5))
print(np.ceil(1.6))

In [ ]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.ceil(mat))

## `floor()`
- helps us rounding off the float values to its nearest minimum value
- Syntax: `np.floor()`

eg.
- if values is 1.4 --> floor value is 1.0
- if values is 1.5 --> floor value is 1.0
- if values is 1.9 --> floor value is 1.0

In [ ]:
print(np.floor(1.4))
print(np.floor(1.5))
print(np.floor(1.6))

In [ ]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.floor(mat))

## `transpose()`
- rotate the matrix
- Syntax : `np.transpose(arr)` or `arr.T`

In [ ]:
mat = np.round(np.random.random((3,4))*100).astype('int32')
print(mat)
print("\n Transpose Matrix")
print(np.transpose(mat))

In [ ]:
mat = np.arange(1,13).reshape(3,4)
print(mat)
print("\n Transpose Matrix")
print(np.transpose(mat))


## `Ravel()`
- used to convert ndarray into 1darray
- Syntax: `np.ravel(arr)`

In [ ]:
mat = np.arange(1,13).reshape(3,4)
print("dimension", mat.ndim)

print("\n")

new_mat = np.ravel(mat)
print("dimension", new_mat.ndim)

## Important Functions

## `Indexing and Slicing in NumPy`

Indexing --> lists[,size-1] --> to have the access over the value

In [ ]:
one_darray = np.arange(1,15)
print(one_darray)
print(one_darray[0])
print(one_darray[2])
print(one_darray[2])
print(one_darray[-1])

In [ ]:
two_darray = np.round(np.random.random((5,5))*100).astype("int32")
print(two_darray)
print('\n col')
print(two_darray[0])


In [ ]:
print(two_darray[0,0])
print(two_darray[4,4])
# two_darray[5,5]IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
three_darray = np.arange(1,9).reshape(2,2,2)
print(three_darray)


In [ ]:
three_darray = np.array([[[1,2,3],[4,5,6]], [[11,12,13],[14,15,16]], [[21,22,23],[24,25,26]]])
print(three_darray)
print(three_darray[0,1,2])
print(three_darray[2,1,1])
# Indexing --> [z-axis, x-axis, y-axis]
# Indexing --> [z-axis, row, col]

## `Slicing`
- similar approach just like the lists
- 2D array : [row : row_2, col_1: col_2]

In [ ]:
two_darray = np.arange(1,17).reshape(4,4)
print(two_darray)
print(two_darray[:,2])
print("---")
print(two_darray[0,:])
print("---")
print(two_darray[2:4])
print("---")
print(two_darray[2:4, 3:4])

In [ ]:
print(two_darray[1:3]) # row 1 to 3 so row 1 and 2 print
print(two_darray[1:3, 1:3])

## `Iterateing over an Array`

In [44]:
array = np.arange(1,10)

for i in array:
    print(i)


1
2
3
4
5
6
7
8
9


In [48]:
array = np.arange(1,10).reshape(3,3)
print(array)

for i in array:
    for j in array:
        print(array[i][j])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [51]:
array = np.arange(1,28).reshape(3,3,3)
# print(array)

for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


## `nditer()`: n dimension iterate function
- help us out with iterating over every value in a nd array
- Synatx: np.nditer()


1D array --> value by value on iteration

2D array --> row by row on iteration

3D array --> 2d array by 2d array

In [52]:
array = np.arange(1,28).reshape(3,3,3)

for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


## `Stacking and Splitting`

### `Stacking`: joining the Arrays Together
- Horizontal Stacking: Row By Row Joining is done
  - Syntax: `np.hstack()`
- Vertical Stacking: Column By Column Joining is done
  - Syntax: `np.vstack()` 

Note: Size of Arrays must be same

In [54]:
mat_1 = np.arange(1,13).reshape(3,4)
mat_2 = np.arange(13,25).reshape(3,4)

print(mat_1)
print(mat_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
horizontal_stacking = np.hstack((mat_1, mat_2))
print(horizontal_stacking)

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
24


In [59]:
vertical_stacking = np.vstack((mat_1, mat_2))
print(vertical_stacking)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


## `Splitting`
- Horizontal Split --> np.hsplit(arr, number of parts you want to be splitted at)
- Vertical Split --> np.vsplit(arr, number of parts)

In [70]:
print("Original Array")
print(vertical_stacking)
np.hsplit(vertical_stacking,2)

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [69]:
print("Original Array")
print(vertical_stacking)
print(np.vsplit(vertical_stacking,2))

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
