# `NumPy Fundamental Formulas`
---

### Installation : `pip install numpy` in your virtual environment

In [ ]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing the NumPy Library

In [2]:
import numpy as np

### `Formulas:` 

## `np.array()`: Creates a NumPy array from Python lists or tuples.
- Creating the Multidimensional Arrays
- Syntax: `np.array(object)`

1D Array or Vector Array

In [3]:
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)
print(type(numpy_array))

# ndarray --> 1d array

[1 2 3 4 5]
<class 'numpy.ndarray'>


2D Array or Matrix Array

In [4]:
# 2D array: matrix array
two_darray = np.array([[1,2,3], [4,5,6]]) # any number row and columen 
print(two_darray)
print(type(two_darray))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


3D Array or Tensors

In [5]:
# 3d Array: tensor array
# z-axis stand for the 3d axis
# x-axis stand for the row
# y-axis stand for the column
three_darray = np.array([[[1,2,3], [4,5,6]],[[8,9,10], [11,23,13]], [[44,55,66], [18,75,100]]])
print(three_darray)

[[[  1   2   3]
  [  4   5   6]]

 [[  8   9  10]
  [ 11  23  13]]

 [[ 44  55  66]
  [ 18  75 100]]]


## `dtype` Parameter 
- which can help us out with deciding about the size of the data we are going to store inside our array

In [6]:
a1 = np.array([1,2,3,4,5], dtype=np.int32)
a2 = np.array([7,8,9,10,11], dtype=np.int64)

print(a1)
print(a2)
# np.float64 or np.float32

[1 2 3 4 5]
[ 7  8  9 10 11]


In [7]:
np.array([1,2,3,4,5], dtype=int)

array([1, 2, 3, 4, 5])

In [8]:
np.array([7,8,9,10,11], dtype=float)

array([ 7.,  8.,  9., 10., 11.])

In [9]:
np.array([7,8,9,10,11,0, -1], dtype=bool)

array([ True,  True,  True,  True,  True, False,  True])

## `np.arange()` 
- Creates values within a range.
- Syntax: `np.arange(start,stop, step)` Note:  like range function in python

In [10]:
# In Python
empty_list = []
for i in range(16):
    empty_list.append(i)

print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [11]:
# In Numpy
r = np.arange(16) # start from 0 by default and end on 16
print(r)

r1 = np.arange(1,16) # start from 1 and end 15 
print(r1)

r2 = np.arange(2,21,2) # start with 2 , end to 21 and step is 2
print(r2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]


## `np.reshape()`
- helps us out with changing the shape of the array 
- Syntax `np.shape(row,column)`

In [12]:
arange_data = np.arange(1,17) # start, end
reshaped_data = arange_data.reshape(4,4) # row, column
reshaped_data2 = arange_data.reshape(2,8) # row, column
# reshaped_data3 = arange_data.reshape(2,9) # ValueError: cannot reshape array of size 16 into shape (2,9
print(reshaped_data)
print(reshaped_data2)
# print(reshaped_data3)

# Note: row * column = should be equal of the length of the array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


## `np.ones()`
- Creates an array filled with ones. ( float value by default )
- Sytax: `np.ones(shape)`

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## `np.zeros()`: 
- Creates an array filled with zeros.
- Syntax: np.zeros(shap)

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## `np.random.random()`
- it helps us out with generating any random values from 0 to 1 inside our matrix
- Syntax: `np.random.random((row,col))`

In [17]:
np.random.random((3,4)) # row , column

array([[0.16011708, 0.97262117, 0.29335573, 0.4177606 ],
       [0.7712996 , 0.53485188, 0.54062964, 0.77204576],
       [0.0370492 , 0.06015422, 0.58143065, 0.61934979]])

## `np.identity()`
- help us out with Returns or creating an identity matrix or Square Matrix ( means, rows == column).
- Syntax: np.identity()

In [18]:
# np.identity((3,4)) # throw error
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## `np.linspace()`
- it make sure that every value with the given range is going to have similar distance from each other
- or, Creates evenly spaced values between two limits.
- Syntax: `np.linspace(start, stop, num)`
 

In [19]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [20]:
np.linspace(-10,10,10) # necessary for machine learning

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## `np.full()`
- Creates an array filled with a specified value
- Syntax: `np.full(shape, value)`

In [21]:
arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


In [22]:
arr = np.full((5, 4), 1)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## `np.empty()`
- Creates an array without initializing entries.
- Sytax: `np.empty(shape)`


In [23]:
arr = np.empty((2, 2))
print(arr)

[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
