# `NumPy Statistical Functions`
---

In [ ]:
import numpy as np

## 1. `mean()`
- mean of all values inside the array and matrix
- Syntax: np.mean()

In [ ]:
arr = np.arange(1,20)
print("mean", np.mean(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Mean of Matrix: ", np.mean(mat))
print("\n")
print("Mean of Columns: ", np.mean(mat, axis= 0))
print("\n")
print("Mean of Rows: ", np.mean(mat, axis = 1))

## 2. `std()`
- provides with the standard deviation of all valeus of the matrix or array
- Syntax: np.std(arr)

In [ ]:
arr = np.arange(1,20)
print("Standard Deviation", np.std(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Standard Deviation of Matrix: ", np.std(mat))
print("\n")
print("Standard Deviation of Columns: ", np.std(mat, axis= 0))
print("\n")
print("Standard Deviation of Rows: ", np.std(mat, axis = 1))

## 3. `median()`
- help us out calculate the Median of all values in the Array or Matrix
- Syntax: `np.median(arr)`

In [ ]:
arr = np.arange(1,20)
print("Median of an array: ", np.median(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Median of Matrix: ", np.median(mat))
print("\n")
print("Median of Columns: ", np.median(mat, axis= 0))
print("\n")
print("Median of Rows: ", np.median(mat, axis = 1))

## 4. `var()`
- calculating the variance of all values inside the array or matrix
- Syntax: np.var()

In [ ]:
arr = np.arange(1,20)
print("Variance of an array: ", np.median(arr))

In [ ]:
mat = np.round(np.random.random((4,4))* 100).astype("int32")
print(mat)
print("\n")
print("Variance of Matrix: ", np.var(mat))
print("\n")
print("Variance of Columns: ", np.var(mat, axis= 0))
print("\n")
print("Variance of Rows: ", np.var(mat, axis = 1))

# `Trigonometric Functions in NumPy`
---

## 1. `sin()`
- sin value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [ ]:
np.sin(30)

## 2. `cos()`
- cos value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [ ]:
np.cos(30)

## 2. `tan()`
- tan value for the value we are going to pass inside it 
- Synaxt: np.sin()

In [ ]:
np.tan(30)

# `DOT Product of Matrix`
---

- No of rows of first matrix is equal to the no. of columns of second matrix
- Syntax: np.dot(matrix1, matrix2)

In [ ]:
mat_1 = np.round(np.random.random((3,4))*100).astype('int32')
mat_2 = np.round(np.random.random((4,3))*100).astype('int32')

print("Mat 1", mat_1)
print("\n")
print("Mat 2", mat_2)
print("\n")
print(np.dot(mat_1,mat_2))

In [ ]:
mat_1 = np.round(np.random.random((3,5))*100).astype('int32')
mat_2 = np.round(np.random.random((4,3))*100).astype('int32')

# print(np.dot(mat_1,mat_2)) # ValueError: shapes (3,5) and (4,3) not aligned: 5 (dim 1) != 4 (dim 0)

## `log()`
- to calculate the log of all values of our Matrix

In [ ]:
mat_1 = np.round(np.random.random((3,5))*100).astype('int32')
print(np.log(mat_1))

# `exp()`:
- exponential of all values inside the Matrix
- Syntax: np.exp()

In [ ]:
mat = np.round(np.random.random((3,5))*100).astype('int32')

print(np.exp(mat))

## `round()`
- helps us rounding off the float values to its nearest possible integer value
- Syntax: np.round()

eg.
- if values is 1.4 --> round off is 0.0
- if values is 1.5 --> round off is 0.0
- if values is 1.6 --> round off is 2.0

In [ ]:
print(np.round(1.4))
print(np.round(1.5))
print(np.round(1.6))

In [ ]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.round(mat))

## `ceil()`
- helps us rounding off the float values to its nearest max value
- Syntax: np.ceil()

eg.
- if values is 1.4 --> ceil value is 2.0
- if values is 1.5 --> ceil value is 2.0
- if values is 1.6 --> ceil value is 2.0

In [44]:
print(np.ceil(1.4))
print(np.ceil(1.5))
print(np.ceil(1.6))

2.0
2.0
2.0


In [46]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.ceil(mat))

[[6.1312182  8.56644175 3.1864581  1.7718945 ]
 [5.39156785 6.23627172 6.93256525 1.66570154]
 [1.23011421 9.32855564 2.52339101 8.09469824]]


[[ 7.  9.  4.  2.]
 [ 6.  7.  7.  2.]
 [ 2. 10.  3.  9.]]


## `floor()`
- helps us rounding off the float values to its nearest in value
- Syntax: `np.ceil()`

eg.
- if values is 1.4 --> floor value is 1.0
- if values is 1.5 --> floor value is 1.0
- if values is 1.9 --> floor value is 1.0

In [45]:
print(np.floor(1.4))
print(np.floor(1.5))
print(np.floor(1.6))

1.0
1.0
1.0


In [47]:
mat =  np.random.random((3,4))*10
print(mat)
print('\n')

print(np.floor(mat))

[[5.77242281 9.79029764 0.09716518 8.61419111]
 [6.79423598 2.30364158 4.52202007 6.81996774]
 [6.06486693 6.98370178 1.7662883  1.41152355]]


[[5. 9. 0. 8.]
 [6. 2. 4. 6.]
 [6. 6. 1. 1.]]
